### PR TITLE
Improved the readability of haley.py

### PR DESCRIPTION
**Pull request by pendingchaos**

### CODE REVIEW

**Comment by michcioperz** [comment]
I don't like some parts of what you did there :P
I'll redo it my own way

**Comment by pendingchaos** [comment]
OK. Just out of curiosity: What parts do you dislike?

**Comment by michcioperz** [comment]
I was plain okay with newlines, I don't think I like you changing == to != and such

**Comment by michcioperz** [comment]
Okay I decided to whatever

**Pull request merged**
